//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LingusticInterface.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LingusticBaseEntities : DbContext
    {
        private static LingusticBaseEntities _context;

        public LingusticBaseEntities()
            : base("name=LingusticBaseEntities")
        {
        }

        public static LingusticBaseEntities GetContext()
        {
            if (_context == null)
                _context = new LingusticBaseEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Text> Text { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
